apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-agents-pv
  namespace: pg-agents
  labels:
    environment: dev
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: db-local-agents
  local:
    path: /mnt/databases/pg-agents
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - asp-node-01