apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-dev-pv
  namespace: pg-dev
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: db-local-dev
  local:
    path: /mnt/databases/pg-dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - asp-node-01