apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-agents-pvc
  namespace: pg-agents
  labels:
    app: postgres
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: db-local-agents