apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: pg-dev
  labels:
    app: postgres
    environment: dev
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432         
      targetPort: 5432    
      name: postgres
  type: ClusterIP 
