apiVersion: v1
kind: PersistentVolume
metadata:
  name: alpha-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: first-nfs
  nfs:
    path: /volume2/k3s-storage
    server: 192.168.68.117